---
- hosts: all
  become: yes
  become_user: true
  become_method: enable
  gather_facts: FALSE
  tasks:
    - name: install java
      yum:
        name: openjdk-8-jre
        state: present
        update_cache: yes
    - name: install elasticsearch
      yum:
        name: elasticsearch
        state: present
        update_cache: yes

    - name: reload systemd config
      systemd: daemon_reload=yes

    - name: enable service elasticsearch and ensure it is not masked
      systemd:
        name: elasticsearch
        enabled: yes
        masked: no

    - name: ensure elasticsearch is running
      systemd: state=started name=elasticsearch
